version: '3'

volumes:
  postgres_data:
    driver: local

networks:
  lab-fp-network:
    driver:
      bridge

services:
  keycloack-postgres:
    container_name: keycloack-postgres
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
     - .keycloack-postgres.env
    ports:
      - 5433:5432
    networks:
      - lab-fp-network

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    env_file:
     - .keycloack.env
    ports:
      - 8080:8080
    depends_on:
      - keycloack-postgres
    networks:
      - lab-fp-network