version: "3.9"

services:  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8075:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=adminbasic
      - ME_CONFIG_BASICAUTH_PASSWORD=pwbasic
    depends_on:
      - mongodb
    networks:
      - lab-mongo
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://adminbasic:pwbasic@localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - lab-mongo
    volumes:   
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb-data:
    name: mongodb-data

networks: 
    lab-mongo:
      driver: bridge